# Generated by Django 3.2.22 on 2023-11-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docuapp', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.TextField(max_length=30),
        ),
    ]
