# Generated by Django 3.2.22 on 2023-11-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docuapp', '0003_auto_20231101_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
