# Generated by Django 4.2.7 on 2023-11-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docuapp', '0005_alter_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(to='docuapp.docpost'),
        ),
    ]
