# Generated by Django 4.2.7 on 2023-11-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docuapp', '0007_remove_profile_favourites_profile_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favourites',
        ),
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='docuapp.docpost'),
        ),
    ]
